### PR TITLE
Merge trixr4kdz/beta to kdahlquist/beta

### PR DESCRIPTION
**Pull request by trixr4kdz**
@jtorre39 and I have cleaned up the remaining global variables Strain and log2FC from readInputSheet, output, and graphs. I've also renamed the field ```.Strain``` in the GRNstruct into ```.strain``` to keep up with the other variable names that we have. Note that this minor change does not affect the names used in the workbooks.

### CODE REVIEW

**Comment by jtorre39** [comment]
While running tests saw that outputTest fails in seven tests. It's odd in that only one file fails 'Sigmoidal_estimation_fixb0_fixP0_graph','file','4-genes_6-edges_artificial-data_Sigmoidal_estimation_fixb-0_fixP-0_graph'

It's only seven tests that fail by verfication.

- testOutputThresholdCorrect
- testOuputWildTypeExpressionCorrect
- testOutputCin5ExpressionCorrect
- testOutputOptimizedProductionRatesCorrect 
- testOutputNetworkOptimizedWeightsCorrect   
- testOutputNetworkOptimizedWeightsNamesCorrect
- testOutputOptimizationDiagnostics 

Will require debugging and further investigation before the branch should be merged.

**Comment by trixr4kdz** [comment]
The cause of the problem was that we ran GRNmodel on that very file inside the sixteen_tests folder, and with the recent corrections that we have made in the names and certain calculations, the previously expected values were overwritten. Juan and I originally hardcoded thet outputTest values directly from the output files we generated over Summer 2015 to check if the output values are actually written to Excel as they should be. In other words, these values are not taken from the lse routine at all, and any small change to these output files would break the outputTest tests. I checked-out/undid changes to that particular .xlsx output file and the tests pass again.

The lesson here is to make sure to not run GRNmodel with files from sixteen_tests if you don't want it to be overwritten. I usually just copy a particular file into the desktop and run that copy instead XP

I'll note it here that once we catch up these sixteen_tests files by running the current version of MATLAB on them, we will need to update the outputTest hardcoded values in the OutputGRNstruct.m file.

**Comment by jtorre39** [comment]
I'm going to run MSE test and also manually compare output values with an older commit and then the branch will be good to merge.

**Comment by cazinge** [comment]
Holding off on merging until I get confirmation that the tests are passing

**Comment by jtorre39** [comment]
After manually comparing output data with this commit and an older commit 27293da from April, the data remains the same and thus passes in this part. Last is to run MSEtest and make sure it passes and then we can merge.

**Pull request merged**
