### PR TITLE
Converting GRNmap to Jekyll

### PR DESCRIPTION
**Pull request by cazinge**
This turned out to be much bigger of a change than I anticipated, but I have my first revision of the site using Jekyll finally up. You can see the current status of how the site would look here: http://cazinge.github.io/GRNmap/

There are still more revisions that need to be done before I feel that we can merge the new build of the site. For example, now that we have Jekyll on the site, we can simplify the process of updating the constantly updated parts of the site. We rarely touch the site, but if there are any planned upgrades to the site in the future, this sort of feature would make everything easier.

I'll get a wiki page on anything I feel is important or confusing after there's more clarity on actions to be taken from here. 

Also, there are many extraneous files that seem to be leftover from the creation of GRNmap's site from GRNsight's. It would probably be best to purge any unneccessary files, but as it stands nothing is being blocked by this.

### CODE REVIEW

**Comment by kdahlquist** [comment]
I'm reviewing the new site and I see that the Google Analytics page counter does not appear to be working; at least, the page counts are not showing up in the footer.

**Comment by kdahlquist** [comment]
Also, the picture on the People page is not appearing on the right top of the page like it should (this picture is troublesome, it often does not behave well.)

**Comment by cazinge** [comment]
@kdahlquist I'm unsure of whether or not the page counter at the bottom works or not. The reason it doesn't work right now is because my repo is hosting the Jekyll version of the site. My repo, however, has a different host than yours does, meaning that I can't get the same data that you can. In theory, it should work, but I need to merge it to be sure. 

Google analytics is unrelated to page counter as far as I know, but it's in a similar camp where I can't find out whether it works or not without merging the new site.

I didn't feel like fixing the people page in this version of the pull request because it required relooking and restructuring the CSS for the site. Will update once it's been taken care of.

**Comment by kdahlquist** [comment]
Then it looks OK to me to merge the pull request and then take care of fixing things on the new site.

**Comment by dondi** [comment]
@cazinge What’s the ETA on merging this? My impression last Wednesday was that this would be done very soon. It will be good to get this wrapped up so we can continue with the new allocation of GRNmap coding tasks. Thanks!

**Comment by cazinge** [comment]
@dondi I've had this as a lower priority due to my Midterms and projects for the coming week, It's around 20-30 minutes worth of work and isn't really something I can idly do due to the fact that I have to resolve the merge conflict and verify the functionality of existing features on the site itself. I was under the impression that I would be expected to do this during the 4 hour time slot that I work for the project on Tuesday nights, but I can find the time to make this change sooner if need be.

**Comment by dondi** [comment]
OK, that’s fine, that’s why I asked. I’ll move this check item to #249 then so that #244 can be closed.

**Pull request closed without merging**
